version: '3.1'


# Default ${TEAMCITY_VERSION} is defined in .env file

# ./buildserver_pgdata - Posgres DB data
# ./data_dir - TeamCity data directory
# ./teamcity-server-logs - logs of primary TeamCity server
# ./agents/agent-1/conf - configuration directory for the first build agent
# ./agents/agent-1/conf - configuration directory for the second build agent

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=teamcity_password 
      - POSTGRES_USER=teamcity_user
      - POSTGRES_DB=teamcity_db
      - PG_DATA=/var/lib/postgresql/data
    ports:
      - "5433:5432"

  teamcity:
    image: jetbrains/teamcity-server:${TEAMCITY_VERSION}
    hostname: teamcity.local
    restart: always
    ports:
      - "8111:8111"
    volumes:
      - ./data_dir:/data/teamcity_server/datadir
      - ./teamcity-server-logs:/opt/teamcity/logs
    depends_on:
      - db

  teamcity-agent-1:
    image: jetbrains/teamcity-agent:${TEAMCITY_VERSION}-linux-sudo
    restart: always
    privileged: true
    volumes:
      - ./agents/agent-1/conf:/data/teamcity_agent/conf
    environment:
      - DOCKER_IN_DOCKER=start
  teamcity-agent-2:
    image: jetbrains/teamcity-agent:${TEAMCITY_VERSION}-linux-sudo
    restart: always
    privileged: true
    volumes:
      - ./agents/agent-2/conf:/data/teamcity_agent/conf
    environment:
      - DOCKER_IN_DOCKER=start

  gitlab:
    image: gitlab/gitlab-ee:latest
    restart: always
    hostname: gitlab.local
    ports:
      - "80:80"
      - "443:443"
      - "22:22"
    volumes:
      - /srv/gitlab-runners/runner-1/config:/etc/gitlab
      - /srv/gitlab-runners/runner-1/logs:/var/log/gitlab
      - /srv/gitlab-runners/runner-1/data:/var/opt/gitlab
    environment:
      - GITLAB_OMNIBUS_CONFIG="external_url 'http://gitlab.local'"
  gitlab-runner-1:
    image: gitlab/gitlab-runner
    restart: always
    volumes:
      - /srv/gitlab-runners/runner-1/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
